# Generated by Django 5.2.1 on 2025-05-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, unique=True, verbose_name='ID пользователя')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя пользователя (если доступно)')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время подписки')),
            ],
            options={
                'verbose_name': 'Подписчик',
                'verbose_name_plural': 'Подписчики',
            },
        ),
    ]
